[package]
name        = "write_avail"
version     = "0.0.1"
keywords    = ["influxdb", "influxdb2", "influxdb-client"]
description = "Influxdb 2 client library for rust"
edition     = "2021"


[profile.release]
opt-level = "z"


[features]
default     = ["native-tls"]
native-tls  = ["reqwest/native-tls"]
rustls      = ["reqwest/rustls-tls"]


[dependencies] # In alphabetical order
futures      = { version = "0.3" }
influxdb2    = { version = "0.3", features = ["rustls"], default-features = false }
prelude      = { version = "0.2" }
reqwest      = { version = "0.11" , features = ["blocking"] }
serde        = "1.0.152"
serde_derive = "1.0.152"
serde_json   = "1.0.93"
tokio        = { version = "1.25", features = ["full"]  }
